server:
  port: 8190
  servlet:
    context-path: /products
eureka:
  client:
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
  application:
    name: front-client
